<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE persona [
    <!ELEMENT persona (nombre, edad, direccion)>
    <!ELEMENT direccion (calle, CP, poblacion)>

    <!ELEMENT nombre (#PCDATA)>
    <!ELEMENT edad (#PCDATA)>
    <!ELEMENT calle (#PCDATA)>
    <!ELEMENT CP (#PCDATA)>
    
    <!ELEMENT poblacion (#PCDATA)>
    <!ATTLIST poblacion tipo CDATA #REQUIRED>
]>

<persona>
    <nombre>Isaac</nombre>
    <edad>28</edad>
    <direccion>
        <calle>Av. CÃ¡diz</calle>
        <CP>18007</CP>
        <poblacion tipo="ciudad">Granada</poblacion>
    </direccion>
</persona>