<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE digidex [
    <!ELEMENT digidex (digimon+)>
    <!ELEMENT digimon (name, id, type, level, abilities, baseStats, registrationDate, legendary?)>
    <!ELEMENT name (#PCDATA)>
    <!ELEMENT id (#PCDATA)>
    <!ELEMENT type (#PCDATA)>
    <!ELEMENT level (#PCDATA)>
    <!ELEMENT abilities (ability+)>
    <!ELEMENT ability (#PCDATA)>
    <!ELEMENT baseStats (HP, ATK, DEF)>
    <!ELEMENT HP (#PCDATA)>
    <!ELEMENT ATK (#PCDATA)>
    <!ELEMENT DEF (#PCDATA)>
    <!ELEMENT registrationDate (#PCDATA)>
    <!ELEMENT legendary EMPTY>
]>
<digidex>
    <digimon>
        <name>Agumon</name>
        <id>DG-0001</id>
        <type>Vaccine</type>
        <level>Rookie</level>
        <abilities>
            <ability>Pepper Breath</ability>
            <ability>Spitfire Blast</ability>
        </abilities>
        <baseStats>
            <HP>100</HP>
            <ATK>70</ATK>
            <DEF>50</DEF>
        </baseStats>
        <registrationDate>2024-01-01</registrationDate>
        <!-- Agumon no es legendario -->
    </digimon>
    <digimon>
        <name>WarGreymon</name>
        <id>DG-0002</id>
        <type>Vaccine</type>
        <level>Mega</level>
        <abilities>
            <ability>Terra Force</ability>
            <ability>Brave Shield</ability>
        </abilities>
        <baseStats>
            <HP>900</HP>
            <ATK>500</ATK>
            <DEF>400</DEF>
        </baseStats>
        <registrationDate>2023-12-15</registrationDate>
        <legendary/>
    </digimon>
</digidex>
